use_frameworks!

platform :ios, '8.0'

target 'XBaseTool_Example' do
  pod 'XBaseTool', :path => '../'

  target 'XBaseTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
